Repository toggl-open-source/toggldesktop, pull requests merged in 2018-12, with the labels that each got.

#2663 Linux settings improvement
  src/ui/linux/TogglDesktop/preferencesdialog.cpp
  src/ui/linux/TogglDesktop/preferencesdialog.h
  src/ui/linux/TogglDesktop/preferencesdialog.ui
  src/ui/linux/TogglDesktop/settingsview.h
  src/ui/linux/TogglDesktop/toggl.cpp
  src/ui/linux/TogglDesktop/toggl.h
Labels: linux

#2634 Trim all leading & trailing space in Description
  src/time_entry.cc
  src/toggl_api_private.cc
  src/toggl_api_private.h
Labels: macOs

#2641 Fix bug: Can't select app on Expose mode if app is "Always on Top" mode
  src/ui/osx/TogglDesktop/MainWindowController.h
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: macOs

#2670 Clear Old User Notifications
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/UserNotificationCenter.h
  src/ui/osx/TogglDesktop/test2/UserNotificationCenter.m
Labels: macOs

#2693 Fix issue when old value of EditView doesn't change
  src/ui/osx/TogglDesktop/TimeEntryEditViewController.m
Labels: macOs

#2689 Resolve warning issues
  src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
  src/toggl_api.h
  src/ui/osx/TogglDesktop/FeedbackWindowController.m
  src/ui/osx/TogglDesktop/TimeEntryEditViewController.m
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/Utils.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/LoadMoreCell.xib
  src/ui/osx/TogglDesktop/test2/NSAlert+Utils.h
  src/ui/osx/TogglDesktop/test2/NSAlert+Utils.m
  src/ui/osx/TogglDesktop/test2/NSCustomComboBox.m
  src/ui/osx/TogglDesktop/test2/UnsupportedNotice.m
  third_party/MASShortcut/MASShortcutView+UserDefaults.m
  third_party/MASShortcut/MASShortcutView.m
  third_party/TFDatePicker/TFDatePicker/TFDatePicker.xcodeproj/project.pbxproj
  third_party/TFDatePicker/TFDatePicker/TFDatePicker/TFDatePicker-Info.plist
  third_party/gtm-oauth2-read-only/Source/GTMOAuth2Authentication.m
  third_party/gtm-oauth2-read-only/Source/Mac/GTMOAuth2Window.xib
  third_party/gtm-oauth2-read-only/Source/Mac/GTMOAuth2WindowController.m
Labels: lib, macOs

#2697 Sync fix
  src/context.cc
Labels: lib

#2631 Upgrade the Toggl AppIcon by using assets
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/Contents.json
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive128x128.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive128x128@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive16x16.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive16x16@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive256x256.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive256x256@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive32x32.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive32x32@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive512x512.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive512x512@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/256x256.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/512x512.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/Contents.json
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/Contents.json
  src/ui/osx/TogglDesktop/app.icns
  src/ui/osx/TogglDesktop/app_inactive.icns
  src/ui/osx/TogglDesktop/test2/AppDelegate.h
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/AppIconFactory.h
  src/ui/osx/TogglDesktop/test2/AppIconFactory.m
  src/ui/osx/TogglDesktop/test2/TogglDesktop-Info.plist
Labels: macOs

#2703 Strange jump in Entry List when the datasource is reloaded
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
Labels: macOs

#2665 Fix the login widget layout (linux)
  src/ui/linux/TogglDesktop/loginwidget.cpp
  src/ui/linux/TogglDesktop/loginwidget.ui
Labels: linux

#2700 Fix most linux warnings
  src/ui/linux/TogglDesktop/clickablelabel.cpp
  src/ui/linux/TogglDesktop/colorpicker.cpp
  src/ui/linux/TogglDesktop/errorviewcontroller.cpp
  src/ui/linux/TogglDesktop/idlenotificationdialog.cpp
  src/ui/linux/TogglDesktop/loginwidget.cpp
  src/ui/linux/TogglDesktop/loginwidget.h
  src/ui/linux/TogglDesktop/main.cpp
  src/ui/linux/TogglDesktop/mainwindowcontroller.cpp
  src/ui/linux/TogglDesktop/overlaywidget.cpp
  src/ui/linux/TogglDesktop/overlaywidget.h
  src/ui/linux/TogglDesktop/preferencesdialog.cpp
  src/ui/linux/TogglDesktop/singleapplication.cpp
  src/ui/linux/TogglDesktop/timeentrycellwidget.cpp
  src/ui/linux/TogglDesktop/timeentryeditorwidget.cpp
  src/ui/linux/TogglDesktop/timeentrylistwidget.cpp
  src/ui/linux/TogglDesktop/timeentrylistwidget.h
  src/ui/linux/TogglDesktop/timeentryview.cpp
  src/ui/linux/TogglDesktop/timerwidget.cpp
  src/ui/linux/TogglDesktop/toggl.cpp
Labels: linux

#2699 Focus on Description TextField in default mode (mac)
  src/ui/osx/TogglDesktop/TimerEditViewController.m
Labels: macOs

#2733 Fix System tray error 'QSystemTrayIcon::setVisible: No Icon set'
  src/ui/linux/TogglDesktop/mainwindowcontroller.cpp
  src/ui/linux/TogglDesktop/systemtray.cpp
  src/ui/linux/TogglDesktop/systemtray.h
Labels: linux
