Repository toggl-open-source/toggldesktop, pull requests merged in 2019-11, with the labels that each got.

#3482 Implement About window design update
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/Resources/toggl-logo-dark.png
  src/ui/windows/TogglDesktop/TogglDesktop/Resources/toggl-logo-light.png
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/HideWindowOnClosingBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ComboBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Hyperlink.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/MahApps.Overrides.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ToolWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/SharedStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/Layout/Comfortable.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/Layout/Compact.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/TimerStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ThemeTypes.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/UIExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/AboutWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/AboutWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/IdleNotificationWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/IdleNotificationWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MiniTimerWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml.cs
Labels: windows

#3484 Detect Windows Light/Dark mode on the app start
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Theme.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ThemeTypes.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Theming/Theme.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Theming/ThemeResourceDictionary.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Theming/ThemeType.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#3497 Fix the Word cut off in Idle Notification
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.xib
Labels: bug, macOs

#3509 Implement Feedback window UI
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/ButtonBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/FocusBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/FocusParentWindowOnClosingBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/BytesToStringConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/FileNameToIconConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/TrimPathConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ComboBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/TextBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ToolWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/FeedbackWindowViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/AboutWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
Labels: windows

#3443 Add identifier to TimeDecoratorView.xib (mac)
  src/ui/osx/TogglDesktop/Feature/TimeEntry/Views/TimeDecoratorView.xib
Labels: bug, macOs

#3504 UI constrains issues when the list is empty
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.xib
Labels: bug, macOs

#3507 Fix the AutoComplete appears unexpectedly when editing the TimeEntry
  src/ui/osx/TogglDesktop/test2/AutoCompleteInput.h
  src/ui/osx/TogglDesktop/test2/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/test2/LiteAutoCompleteDataSource.m
Labels: bug, macOs

#3501 Fix wrong duration value when compressing the events
  src/timeline_event.cc
  src/timeline_event.h
  src/user.cc
Labels: bug, macOs

#3527 Update 10 unique TE in touchbar
  src/ui/osx/TogglDesktop/Feature/TouchBar/TouchBarService.swift
Labels: macOs

#3541 Show selected task name in edit view project input
  src/ui/osx/Gemfile
  src/ui/osx/Gemfile.lock
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/ProjectAutoCompleteTextField.swift
Labels: bug, macOs

#3540 Fix the edit popup closing right after open when clicking on projec tlabel
  src/ui/osx/TogglDesktop/test2/ProjectTextField.m
Labels: bug, macOs

#3548 Add F5 as Sync hotkey
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
Labels: windows

#3550 Better tooltip for tray icon
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/EmptyStringToCollapsedConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TrayToolTipControl.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TrayToolTipControl.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#3549 Fix tagging so the main build workflow actually runs on a new release
  .github/workflows/pr_tagger.yml
Labels: actions

#3339 [LibOverhaul 04] Initialize all class members
  src/gui.h
Labels: lib

#3340 [LibOverhaul 05] Use the prefix increment operator
  src/batch_update_result.cc
  src/context.cc
  src/formatter.cc
  src/gui.cc
  src/help_article.cc
  src/related_data.cc
  src/time_entry.cc
  src/toggl_api_private.cc
  src/user.cc
Labels: lib

#3341 [LibOverhaul 06] Mark override methods
  src/autotracker.h
  src/client.h
  src/context.h
  src/gui.h
  src/https_client.h
  src/obm_action.h
  src/project.h
  src/settings.h
  src/tag.h
  src/task.h
  src/time_entry.h
  src/timeline_event.h
  src/user.h
  src/workspace.h
Labels: lib

#3495 Run our test suite on Linux in GitHub Actions
  .github/workflows/main.yml
  dist/run-tests.sh
  src/test/toggl_api_test.cc
Labels: actions

#3554 Add macOS to GitHub Actions
  .github/workflows/main.yml
  dist/osx/build.sh
Labels: actions

#3343 [LibOverhaul 07] Seed the random number generator only once
  src/CMakeLists.txt
  src/context.cc
  src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj.filters
  src/migrations.cc
  src/random.cc
  src/random.h
  src/websocket_client.cc
Labels: lib
