Repository toggl-open-source/toggldesktop, pull requests merged in 2019-02, with the labels that each got.

#2676 Linux autocomplete
  src/ui/linux/TogglDesktop/CMakeLists.txt
  src/ui/linux/TogglDesktop/TogglDesktop.pro
  src/ui/linux/TogglDesktop/autocompletecombobox.cpp
  src/ui/linux/TogglDesktop/autocompletecombobox.h
  src/ui/linux/TogglDesktop/autocompletelistmodel.cpp
  src/ui/linux/TogglDesktop/autocompletelistmodel.h
  src/ui/linux/TogglDesktop/autocompletelistview.cpp
  src/ui/linux/TogglDesktop/autocompletelistview.h
  src/ui/linux/TogglDesktop/autocompleteview.h
  src/ui/linux/TogglDesktop/timeentryeditorwidget.cpp
  src/ui/linux/TogglDesktop/timeentryeditorwidget.h
  src/ui/linux/TogglDesktop/timeentryeditorwidget.ui
  src/ui/linux/TogglDesktop/timeentryview.cpp
  src/ui/linux/TogglDesktop/timeentryview.h
  src/ui/linux/TogglDesktop/timerwidget.cpp
  src/ui/linux/TogglDesktop/timerwidget.h
  src/ui/linux/TogglDesktop/timerwidget.ui
Labels: linux

#2774 New Login and Sign up UI
  src/ui/osx/TogglDesktop/AboutWindowController.m
  src/ui/osx/TogglDesktop/LoginViewController.h
  src/ui/osx/TogglDesktop/LoginViewController.m
  src/ui/osx/TogglDesktop/LoginViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.h
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/MainWindowController.xib
  src/ui/osx/TogglDesktop/Media.xcassets/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/background-pattern.imageset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/background-pattern.imageset/pattern_dark@2x.jpg
  src/ui/osx/TogglDesktop/Media.xcassets/background-pattern.imageset/pattern_light@2x.jpg
  src/ui/osx/TogglDesktop/Media.xcassets/close-button.imageset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/close-button.imageset/close-button.png
  src/ui/osx/TogglDesktop/Media.xcassets/close-button.imageset/close-button@2x.png
  src/ui/osx/TogglDesktop/Media.xcassets/error-background-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/error-title-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/google-logo.imageset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/google-logo.imageset/group-2.png
  src/ui/osx/TogglDesktop/Media.xcassets/google-logo.imageset/group-2@2x.png
  src/ui/osx/TogglDesktop/Media.xcassets/login-button-background.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/login-button-foreground.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/login-text-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/toggl-logo.imageset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/toggl-logo.imageset/toggl-logo-1.png
  src/ui/osx/TogglDesktop/Media.xcassets/toggl-logo.imageset/toggl-logo-2.png
  src/ui/osx/TogglDesktop/Media.xcassets/toggl-logo.imageset/toggl-logo.png
  src/ui/osx/TogglDesktop/Media.xcassets/toggl-logo.imageset/toggl-logo@2x-1.png
  src/ui/osx/TogglDesktop/Media.xcassets/toggl-logo.imageset/toggl-logo@2x-2.png
  src/ui/osx/TogglDesktop/Media.xcassets/toggl-logo.imageset/toggl-logo@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/FlatButton.swift
  src/ui/osx/TogglDesktop/test2/FloatingErrorView.swift
  src/ui/osx/TogglDesktop/test2/FloatingErrorView.xib
  src/ui/osx/TogglDesktop/test2/NSCustomComboBox.m
  src/ui/osx/TogglDesktop/test2/NSTextFieldClickable.h
  src/ui/osx/TogglDesktop/test2/NSTextFieldClickable.m
  src/ui/osx/TogglDesktop/test2/NSTextFieldClickablePointer.m
  src/ui/osx/TogglDesktop/test2/NSView+Xib.swift
Labels: macOs

#2802 Parse error message if response is JSON (lib), #2431
  src/https_client.cc
Labels: lib

#2776 Improve/remove sync delay
  src/context.cc
  src/context.h
Labels: lib

#2743 Restore / Save current windows frame in Linux
  src/ui/linux/TogglDesktop/mainwindowcontroller.cpp
  src/ui/linux/TogglDesktop/mainwindowcontroller.h
  src/ui/linux/TogglDesktop/toggl.cpp
  src/ui/linux/TogglDesktop/toggl.h
Labels: linux

#2798 Make the General tab the default in Preferences (linux)
  src/ui/linux/TogglDesktop/preferencesdialog.ui
Labels: linux

#2792 Update new color scheme for title in Login/Signup
  src/ui/osx/TogglDesktop/LoginViewController.xib
  src/ui/osx/TogglDesktop/Media.xcassets/login-text-color.colorset/Contents.json
Labels: macOs

#2800 New Preference design
  src/ui/osx/TogglDesktop/Media.xcassets/error-background-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/preference-background-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/preference-box-background-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/PreferencesWindowController.h
  src/ui/osx/TogglDesktop/PreferencesWindowController.m
  src/ui/osx/TogglDesktop/PreferencesWindowController.xib
Labels: macOs

#2794 New logo for macOS app
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/Contents.json
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive128x128.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive128x128@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive16x16.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive16x16@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive256x256.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive256x256@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive32x32.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive32x32@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive512x512.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/app_inactive512x512@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_128@1x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_128@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_16@1x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_16@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_256@1x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_256@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_32@1x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_32@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_512@1x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIcon.appiconset/icon_512@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/256x256.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/512x512.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/Contents.json
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/red.png
  src/ui/osx/TogglDesktop/TogglDesktop/Images.xcassets/AppIconActive.imageset/red@2x.png
  src/ui/osx/TogglDesktop/app_icon_pdf.pdf
Labels: macOs
