Repository toggl-open-source/toggldesktop, pull requests merged in 2019-10, with the labels that each got.

#3388 Alternative solution for handling 429 error message
  src/const.h
  src/context.cc
  src/gui.cc
Labels: lib

#3363 Run Store app on startup
  src/ui/windows/TogglDesktop/TogglDesktop.Package/Package.appxmanifest
  src/ui/windows/TogglDesktop/TogglDesktop.Package/TogglDesktop.Package.wapproj
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/Win10/RunOnStartup.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml.cs
Labels: WIP, windows

#3396 Only format the TogglDeskop source (mac)
  Makefile
Labels: macOs

#3418 Improve logic how we present the Create Tag button
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/DataSource/TagDataSource.swift
Labels: macOs

#3055 [help wanted][WIP] Make tests work again and work in Linux
  .gitignore
  CMakeLists.txt
  Makefile
  src/autotracker.h
  src/base_model.h
  src/batch_update_result.h
  src/client.h
  src/context.cc
  src/context.h
  src/database.h
  src/feedback.h
  src/formatter.cc
  src/formatter.h
  src/get_focused_window_linux.cc
  src/gui.cc
  src/gui.h
  src/help_article.h
  src/https_client.h
  src/idle.h
  src/lib/windows/TogglDesktopDLL.Tests/TogglDesktopDLL.Tests.vcxproj
  src/lib/windows/TogglDesktopDLL.Tests/packages.config
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj
  src/migrations.h
  src/netconf.h
  src/obm_action.h
  src/project.h
  src/proxy.h
  src/rectangle.h
  src/related_data.h
  src/settings.h
  src/tag.h
  src/task.h
  src/test/CMakeLists.txt
  src/test/app_test.cc
  src/test/test_data.cc
  src/test/test_data.h
  src/test/toggl_api_test.cc
  src/test/toggl_api_test.h
  src/time_entry.h
  src/timeline_event.h
  src/timeline_notifications.h
  src/timeline_uploader.h
  src/toggl_api.h
  src/toggl_api_private.cc
  src/toggl_api_private.h
  src/types.h
  src/ui/windows/TogglDesktop/TogglDesktop.sln
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
  src/user.h
  src/websocket_client.h
  src/window_change_recorder.h
  src/workspace.h
  testdata/me.json
  third_party/CMakeLists.txt
Labels: WIP, lib

#3401 Fix memory leaks in View List handling
  src/toggl_api_private.cc
  src/ui/linux/TogglDesktop/autocompletelistmodel.cpp
Labels: lib

#3419 Able to click on Project labl in AutoComplete Cell (mac)
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/test2/ProjectTextField.m
Labels: bug, macOs

#3405 Implement Google Login for the Linux app
  src/ui/linux/TogglDesktop/loginwidget.cpp
  src/ui/linux/TogglDesktop/loginwidget.h
  src/ui/linux/TogglDesktop/loginwidget.ui
  src/ui/linux/TogglDesktop/toggl.cpp
  src/ui/linux/TogglDesktop/toggl.h
  third_party/qt-oauth-lib/logindialog.cpp
  third_party/qt-oauth-lib/logindialog.h
  third_party/qt-oauth-lib/logindialog.ui
  third_party/qt-oauth-lib/ui_logindialog.h
Labels: linux

#3439 Highlight all tag text field after selection
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/AutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
Labels: macOs

#3462 Don't Update Duration, Start and End Text Field if it's editing
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
Labels: bug, macOs

#3463 Incorrect Timer State when stopping by Pomodoro
  src/ui/osx/TogglDesktop/TimerEditViewController.m
Labels: bug, macOs

#3441 Remove Tag by backspace
  src/ui/osx/TogglDesktop/Feature/Calendar/CalendarViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Key.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Tag/TagTokenView.swift
Labels: bug, macOs
