Repository toggl-open-source/toggldesktop, pull requests merged in 2019-12, with the labels that each got.

#3572 Zoom hotkey in Timeline
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/test2/Base.lproj/MainMenu.xib
Labels: macOs

#3573 Make to_char_t thread-safe (win)
  src/toggl_api_private.cc
Labels: windows

#3569 Titlebar design update implementation
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ContextMenu.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Window.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/UIExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/chrome/ChromelessWindow.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MiniTimerWindow.xaml.cs
Labels: windows

#3530 Fix new Timeline APIs for Window and Linux
  src/gui.cc
  src/test/app_test.cc
  src/test/toggl_api_test.cc
  src/toggl_api.cc
  src/toggl_api.h
  src/toggl_api_private.cc
  src/ui/linux/TogglDesktop/toggl.cpp
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
Labels: macOs

#3576 No duplication TimeEntry in Touch Bar
  src/ui/osx/TogglDesktop/Feature/TouchBar/TouchBarService.swift
  src/ui/osx/TogglDesktop/TimeEntryViewItem.h
  src/ui/osx/TogglDesktop/TimeEntryViewItem.m
Labels: bug

#3578 Add in-app message fetching to library
  src/context.cc
  src/context.h
  src/database.cc
  src/database.h
  src/gui.cc
  src/gui.h
  src/migrations.cc
  src/toggl_api.cc
  src/toggl_api.h
Labels: lib

#3582 Create Zero Time Entry Issues
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: bug, macOs

#3584 Improve in-app message logic
  src/analytics.cc
  src/analytics.h
  src/const.h
  src/context.cc
  src/context.h
  src/toggl_api.cc
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: lib

#3589 InAppMessage improvement
  src/context.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/InAppMessage/InAppMessageViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
Labels: macOs

#3586 In-app Message View (Windows)
  Makefile
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/StringToUpperConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/InAppNotification.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/InAppNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#3553 Make sure syncing is performed after coming back from sleep (lib)
  src/const.h
  src/context.cc
Labels: lib

#3592 Improve/in app messaging fine tuning
  src/context.cc
Labels: lib

#3599 Fix crash with ArgumentException due to invalid mini timer width setting
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Utils.cs
Labels: windows

#3596 The Client Creator view is dismissed when the TE is running
  src/ui/osx/TogglDesktop/TimerEditViewController.m
Labels: bug, macOs

#3608 Increase how the Overlap of Two TEs are
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineTimeEntry.swift
Labels: macOs

#3609 Fix Blur text in non-retina screen
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
Labels: bug, macOs

#3610 Fix Tag AutoComplete jump issues
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/DataSource/TagDataSource.swift
Labels: bug, macOs

#3593 Touch Bar Crash in OSX 10.11
  src/ui/osx/TogglDesktop/LoginViewController.m
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/AppIconFactory.m
  src/ui/osx/TogglDesktop/test2/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.m
  src/ui/osx/TogglDesktop/test2/TouchBar+PrivateAPIs.h
Labels: bug, macOs

#3620 Add missing weak import DFRFoundation
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: bug, macOs

#3630 Fix grouping tasks in AutoComplete
  src/ui/osx/TogglDesktop/test2/LiteAutoCompleteDataSource.m
Labels: bug, macOs

#3627 AutoCompleteView doesn't show in External monitor
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
Labels: bug, macOs

#3615 Added 'New year's Campaign 2020' in-app message
  releases/message.json
Labels: macOs, windows

#3640 Focus main window when receiving an idle notification (linux)
  src/ui/linux/TogglDesktop/idlenotificationwidget.cpp
Labels: linux

#3645 Show the UI briefly before hiding it to start syncing data (linux)
  src/ui/linux/TogglDesktop/main.cpp
Labels: linux

#3647 Change Duration setting enables by default
  src/migrations.cc
Labels: macOs

#3638 Fix linux update notifications (linux)
  dist/linux/debian/rules
  src/CMakeLists.txt
  src/const.h
  src/context.cc
Labels: linux
