Repository toggl-open-source/toggldesktop, pull requests merged in 2019-09, with the labels that each got.

#3276 Fix crash when opening browser link
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/AboutWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/LinqExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Utils.cs
Labels: windows

#3280 Sign up with Google on Windows
  src/context.cc
  src/context.h
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj.filters
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/IdleNotificationWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml.cs
Labels: lib, windows

#3289 Process Tag in background
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Storage/TagStorage.swift
Labels: bug, macOs

#3286 Random Project Color
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectColor.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
Labels: macOs

#3273 Invert color issues
  src/ui/osx/TogglDesktop/Swift/Extensions/NSColor+VisibleColor.swift
Labels: macOs

#3296 Improve solution for bad color contrast in dark mode
  src/ui/osx/TogglDesktop/Swift/Extensions/NSColor+VisibleColor.swift
Labels: macOs

#3299 Limited the maximum height of Activity Timeline
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineActivity.swift
Labels: macOs

#3301 Fix Editor couldn't update data from auto complete (mac)
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
Labels: macOs

#3292 Fix for the main window staying in the tray
  src/ui/windows/TogglDesktop/TogglDesktop/BugsnagService.cs
  src/ui/windows/TogglDesktop/TogglDesktop/Program.cs
  src/ui/windows/TogglDesktop/TogglDesktop/SingleInstanceManager.cs
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/KeyboardShortcuts.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/UIExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Win32.cs
Labels: windows

#3304 Fix crash when showing notification
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/NotificationExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PomodoroNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ReminderNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#3318 Remove recursion from clearing generic view items
  src/gui.cc
  src/toggl_api_private.cc
  src/toggl_api_private.h
Labels: lib

#3322 Added start/continue/stop menu items to dock menu
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: enhancement, macOs

#3329 Avoid using recursion to clear any View items
  src/gui.cc
  src/toggl_api_private.cc
  src/toggl_api_private.h
Labels: lib

#3337 Fix starting new timer with menubar menu item
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: bug, macOs

#3342 Remove compact mode api
  src/context.cc
  src/context.h
  src/database.cc
  src/database.h
  src/migrations.cc
  src/test/toggl_api_test.cc
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
Labels: lib

#3327 Fix issues with database insert triggering instead of update
  src/database.cc
Labels: lib

#3355 Fix Tag AutoComplete couldn't hide
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/TagAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
Labels: bug, macOs

#3360 Properly react to PC shutdown
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#3367 Add Tooltip which displays time up to seconds precision
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml.cs
Labels: macOs, windows
