Repository toggl-open-source/toggldesktop, pull requests merged in 2019-01, with the labels that each got.

#2740 Fixed Crashreporter path script path (mac), closes #2738
  Makefile
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOs

#2748 ScopedLock for RelatedData.TimeEntries
  src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
  src/related_data.cc
  src/related_data.h
  src/user.cc
Labels: lib

#2762 Unable to build `master` on Windows
  src/related_data.h
Labels: lib

#2727 Stop running timer if OS shutdowns or sleep
  src/analytics.cc
  src/context.cc
  src/context.h
  src/database.cc
  src/database.h
  src/gui.h
  src/migrations.cc
  src/related_data.h
  src/settings.cc
  src/settings.h
  src/toggl_api.cc
  src/toggl_api.h
  src/toggl_api_private.cc
  src/ui/linux/TogglDesktop/CMakeLists.txt
  src/ui/linux/TogglDesktop/mainwindowcontroller.cpp
  src/ui/linux/TogglDesktop/mainwindowcontroller.h
  src/ui/linux/TogglDesktop/powermanagement.cpp
  src/ui/linux/TogglDesktop/powermanagement.h
  src/ui/linux/TogglDesktop/preferencesdialog.cpp
  src/ui/linux/TogglDesktop/preferencesdialog.h
  src/ui/linux/TogglDesktop/preferencesdialog.ui
  src/ui/linux/TogglDesktop/settingsview.h
  src/ui/linux/TogglDesktop/toggl.cpp
  src/ui/linux/TogglDesktop/toggl.h
  src/ui/osx/TogglDesktop/PreferencesWindowController.m
  src/ui/osx/TogglDesktop/PreferencesWindowController.xib
  src/ui/osx/TogglDesktop/Settings.h
  src/ui/osx/TogglDesktop/Settings.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/SystemService.h
  src/ui/osx/TogglDesktop/test2/SystemService.m
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml.cs
Labels: lib, linux, macOs, windows

#2753 Refactor NotificationCenter
  src/ui/osx/TogglDesktop/AutocompleteDataSource.m
  src/ui/osx/TogglDesktop/LoginViewController.m
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/PreferencesWindowController.m
  src/ui/osx/TogglDesktop/TimeEntryEditViewController.m
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.m
  src/ui/osx/TogglDesktop/test2/LiteAutoCompleteDataSource.m
  src/ui/osx/TogglDesktop/test2/NSCustomTimerComboBox.m
  src/ui/osx/TogglDesktop/test2/NSTextFieldClickable.m
  src/ui/osx/TogglDesktop/test2/NSUnstripedTableView.m
  src/ui/osx/TogglDesktop/test2/NSViewEscapable.m
  src/ui/osx/TogglDesktop/test2/NotificationCenter+MainThread.swift
  src/ui/osx/TogglDesktop/test2/TimeEntryCell.m
Labels: macOs

#2761 Adopt dark theme from OS
  src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/FeedbackWindowController.xib
  src/ui/osx/TogglDesktop/LoginViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.xib
  src/ui/osx/TogglDesktop/PreferencesWindowController.xib
  src/ui/osx/TogglDesktop/TimeEntryEditViewController.h
  src/ui/osx/TogglDesktop/TimeEntryEditViewController.m
  src/ui/osx/TogglDesktop/TimeEntryEditViewController.xib
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimeEntryListViewController.xib
  src/ui/osx/TogglDesktop/TimerEditViewController.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/AutoCompleteTableCell.xib
  src/ui/osx/TogglDesktop/test2/LoadMoreCell.xib
  src/ui/osx/TogglDesktop/test2/NSColor+Utils.swift
  src/ui/osx/TogglDesktop/test2/NSCustomComboBox.m
  src/ui/osx/TogglDesktop/test2/NSCustomTimerComboBox.m
  src/ui/osx/TogglDesktop/test2/NSTextFieldClickable.m
  src/ui/osx/TogglDesktop/test2/NSTextFieldDuration.m
  src/ui/osx/TogglDesktop/test2/OverlayViewController.xib
  src/ui/osx/TogglDesktop/test2/Theme+Notification.swift
  src/ui/osx/TogglDesktop/test2/Theme.swift
  src/ui/osx/TogglDesktop/test2/TimeEntryCell.m
  src/ui/osx/TogglDesktop/test2/TimeEntryCell.xib
  src/ui/osx/TogglDesktop/test2/TimeEntryCellWithHeader.xib
Labels: 10.14, macOs

#2777 Upgrade Google.Apis.Auth on Windows
  src/ui/windows/TogglDesktop/TogglDesktop/App.config
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/packages.config
  src/ui/windows/TogglDesktop/TogglDesktopDLLInteropTest/app.config
Labels: bug, windows
