Repository toggl-open-source/toggldesktop, pull requests merged in 2019-06, with the labels that each got.

#2995 Fixed toggl_api.h format so csapi generation would work
  src/toggl_api.h
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
Labels: windows

#3010 Fixed keyboard support for idle popup (mac), #2888
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.xib
Labels: macOs

#3023 Idle design
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.h
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.m
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.xib
Labels: good first issue

#3033 Timeline: Tab view selection
  src/gui.h
  src/ui/osx/TogglDesktop/Diff/TogglDesktop-Bridging-Header.h
  src/ui/osx/TogglDesktop/Feature/Timeline/MainDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/MainDashboardViewController.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.h
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/Media.xcassets/tab-view-text-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/TimeEntryListViewController.h
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimeEntryListViewController.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/BetterFocusAutoCompleteInput.h
  src/ui/osx/TogglDesktop/test2/FlatButton.swift
  src/ui/osx/TogglDesktop/test2/TimerContainerBox.swift
Labels: good first issue, macOs

#3029 Keyboard issue on Tag Input
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AddTagButton.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/AutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/TagAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: good first issue

#3042 Focus textfields on Editor
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.xib
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/test2/TimeEntryCell.m
Labels: good first issue

#3043 Resizable Editor Popover and Tool tip
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/AutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorPopover.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.xib
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/NoVibrantPopoverView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/ResizablePopover.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Tag/TagCellView.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/ProjectTextField.m
Labels: good first issue
