Repository toggl-open-source/toggldesktop, pull requests merged in 2019-08, with the labels that each got.

#3174 Fix Crash due to window position being saved with Int64.MinValue
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Utils.cs
Labels: windows

#3177 Autocomplete should be inside the Screen
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
Labels: macOs

#3141 Improve keyboard
  src/ui/osx/TogglDesktop/Feature/TimeEntry/TimeEntryDatasource.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntry/Views/TimeEntryCollectionView.h
  src/ui/osx/TogglDesktop/Feature/TimeEntry/Views/TimeEntryCollectionView.m
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorPopover.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/NoVibrantPopoverView.swift
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimeEntryListViewController.xib
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/TimerEditViewController.xib
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/Utils.h
  src/ui/osx/TogglDesktop/Utils.m
Labels: macOs

#3179 Try to find a possible version string in git if none provided
  CMakeLists.txt
Labels: linux

#3154 Show/hide console menu item in Debug or Prod (mac)
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/Base.lproj/MainMenu.xib
Labels: macOs

#3175 Remove unused dependencies (Windows)
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
Labels: windows

#3159 Get rid of TogglDesktopUpdater
  src/ui/windows/TogglDesktop/TogglDesktop.sln
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/App.config
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/MainForm.Designer.cs
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/MainForm.cs
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/MainForm.resx
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/Program.cs
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/Properties/AssemblyInfo.cs
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/Properties/Resources.Designer.cs
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/Properties/Resources.resx
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/Properties/Settings.Designer.cs
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/Properties/Settings.settings
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/TogglDesktopUpdater.csproj
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/Microsoft.Web.Infrastructure.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/Newtonsoft.Json.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/System.Net.Http.Formatting.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/System.Web.Http.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/System.Web.Mvc.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/System.Web.Razor.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/System.Web.WebPages.Deployment.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/System.Web.WebPages.Razor.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/System.Web.WebPages.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Debug/TogglDesktopUpdater.exe.config
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/Microsoft.Web.Infrastructure.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/System.Net.Http.Formatting.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/System.Web.Http.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/System.Web.Mvc.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/System.Web.Razor.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/System.Web.WebPages.Deployment.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/System.Web.WebPages.Razor.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/System.Web.WebPages.xml
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/TogglDesktopUpdater.exe.config
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/TogglDesktopUpdater.vshost.exe.config
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/bin/Release/TogglDesktopUpdater.vshost.exe.manifest
  src/ui/windows/TogglDesktop/TogglDesktopUpdater/toggl.ico
Labels: windows

#3192 Fix window showing up outside screen
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Utils.cs
Labels: windows

#3194 Clean up Windows build configs
  README.md
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj
  src/ui/windows/TogglDesktop/TogglDesktop.sln
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
Labels: windows

#3200 Actually destroy TogglApi context when quitting the app
  src/ui/linux/TogglDesktop/mainwindowcontroller.cpp
  src/ui/linux/TogglDesktop/toggl.cpp
Labels: linux

#3198 Track Edit size after resizing
  src/analytics.cc
  src/analytics.h
  src/context.cc
  src/context.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
Labels: macOs

#3199 Adapt color for light/dark mode
  src/ui/osx/TogglDesktop/Feature/TimeEntry/Views/DotImageView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/ProjectAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Swift/Extensions/NSColor+VisibleColor.swift
  src/ui/osx/TogglDesktop/Swift/Extensions/NSView+Appearance.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/ProjectTextField.m
Labels: macOs

#3203 Resolve conflicted TimeEntry in Timeline
  src/context.cc
  src/context.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineData.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineTimeEntry.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineTimeEntryCell.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineTimeEntryMenu.swift
  src/ui/osx/TogglDesktop/test2/Reachability.m
Labels: macOs

#3207 Fix lose focus on Editor when TE is running
  src/ui/osx/TogglDesktop/TimerEditViewController.m
Labels: macOs

#3213 Tab to focus on "Add tag"
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AddTagButton.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.xib
Labels: macOs

#3215 Project is clear after creating
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/ProjectAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
Labels: macOs

#3216 AutoCompleteView is behind the Dock Bar
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
Labels: macOs

#3218 Show Window and focus (mac)
  src/ui/osx/TogglDesktop/Swift/Extensions/NSWindowController+Focusable.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: macOs

#3217 Highlight the group that is being collapsed
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCell.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml.cs
Labels: windows

#3224 Fix crash when locking or going to sleep while being logged out
  src/context.cc
Labels: lib

#3223 Disable return key in AutoCompleteTextField (mac)
  src/ui/osx/TogglDesktop/Feature/Calendar/CalendarViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/Input/AutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/CursorButton.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Key.swift
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimerEditViewController.h
  src/ui/osx/TogglDesktop/TimerEditViewController.m
Labels: macOs

#3226 Fix decimal durations not displaying correctly (lib)
  src/formatter.cc
Labels: lib

#3227 Graceful error handling during auto-update
  src/ui/windows/TogglDesktop/TogglDesktop/Program.cs
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/AboutWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Utils.cs
Labels: windows

#3239 Clean up Idle Notifications code and fix hiding of the widget
  src/ui/linux/TogglDesktop/idlenotificationwidget.cpp
  src/ui/linux/TogglDesktop/idlenotificationwidget.h
  src/ui/linux/TogglDesktop/idlenotificationwidget.ui
Labels: linux

#3241 Avoid overriding the TE in Timer when selecting from AutoComplete
  src/ui/osx/TogglDesktop/TimerEditViewController.m
Labels: macOs

#3243 Missing Tag in AutoComplete
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
Labels: macOs

#3252 Set the default size of the window (win)
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Utils.cs
Labels: windows

#3259 Added WID to time entry hash generation (lib), closes #3255
  src/time_entry.cc
Labels: lib

#3254 Fix Private/Public project when creating new one
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.xib
Labels: macOs

#3256 Load More in Timeline
  src/ui/osx/TogglDesktop/Feature/TimeEntry/TimeEntryDatasource.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/MainDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/TimeEntryListViewController.h
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
Labels: macOs

#3248 Minor New Design Improvements
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Tag/TagCellView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Tag/TagCellView.xib
Labels: macOs

#3264 Treat "This entry can't be saved - please add..." errors as user errors
  src/const.h
  src/error.cc
Labels: lib

#3262 Remove Copy_pocos in makefile
  Makefile
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOs

#3265 Attempt to fix the Window size when it goes smaller than Timer Bar
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/MainWindowController.xib
  src/ui/osx/TogglDesktop/TimeEntryListViewController.h
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
Labels: macOs
