Repository toggl-open-source/toggldesktop, pull requests merged in 2020-05, with the labels that each got.

#4023 Rename 'Kopsik' to Toggl in Application Support
  src/ui/osx/TogglDesktop/Utils.m
Labels: macOs

#4039 Continue does not attach archived project
  src/model/user.cc
Labels: lib

#4037 Clear default project if it has been archived
  src/model/user.cc
Labels: macOs

#4036 Added simple filtering to default project combobox
  src/ui/osx/TogglDesktop/PreferencesWindowController.m
Labels: macOs

#4047 Update new list of Project Colors
  src/model/project.cc
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorPickerView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorViewItem.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectColor.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectColorPicker.xaml
Labels: lib, linux, macOs, windows

#4040 Use server sent error message in case of required fields error
  src/context.cc
Labels: lib

#4053 Add duration textbox to the mini timer
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/MiniTimer.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/MiniTimer.xaml.cs
Labels: windows

#4054 Fix failed ProjectColor Test
  src/test/app_test.cc
Labels: bug, lib

#4057 Delete old updates only if there are no pending updates
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
Labels: bug, windows

#4061 Default Project Color
  src/ui/osx/TogglDesktop/Feature/ColorWheel/ColorGraphicsView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorPickerView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorPickerView.xib
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectColor.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
Labels: macOs

#4059 Password Strength View
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/DSFSecureTextField.swift
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordRuleView.swift
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordRuleView.xib
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordStrengthValidation.swift
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordStrengthView.swift
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordStrengthView.xib
  src/ui/osx/TogglDesktop/LoginViewController.m
  src/ui/osx/TogglDesktop/LoginViewController.xib
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password-eye-close.imageset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password-eye-close.imageset/not visible.png
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password-eye-close.imageset/not visible@2x.png
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password-eye-open.imageset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password-eye-open.imageset/Group.png
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password-eye-open.imageset/Group@2x.png
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password_green_check.imageset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password_green_check.imageset/Group.png
  src/ui/osx/TogglDesktop/Media.xcassets/Login/password_green_check.imageset/Group@2x.png
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOs

#4049 Fixed Exception if the project name exists
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
Labels: bug, macOs

#4072 Support multiple-time Undo/Redo for deleting TimeEntry
  src/context.cc
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Undo/UndoManager.swift
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
Labels: macOs

#4079 Fix the max size of Preferences window
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml.cs
Labels: windows

#3659 Fix how we trigger Pomodoro if we update Start / Duration in current running Time Entry
  src/context.cc
  src/context.h
  src/model/time_entry.cc
  src/model/time_entry.h
Labels: bug, lib

#4084 Remove focus from app after closing with global shortcut (mac), #1824
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: bug, macOs

#4070 Reset LoginViewController after login/signup
  src/context.cc
  src/https_client.h
  src/ui/osx/TogglDesktop/LoginViewController.m
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: bug, macOs

#4092 Added user check to loading time entries list
  src/context.cc
Labels: lib

#4093 Fixed send feedback menu item tag
  src/ui/osx/TogglDesktop/test2/Base.lproj/MainMenu.xib
Labels: macOs

#4082 Memory Leaking - v3
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorPickerView.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorPickerView.xib
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorViewItem.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ColorViewItem.xib
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: bug, macOs

#4075 Fix Onboarding crash on Window/Linux
  Makefile
  src/CMakeLists.txt
  src/context.cc
  src/context.h
  src/cpptime.h
  src/database/database.cc
  src/database/database.h
  src/database/migrations.cc
  src/database/migrations.h
  src/gui.cc
  src/gui.h
  src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj.filters
  src/model/user.cc
  src/model/user.h
  src/onboarding_service.cpp
  src/onboarding_service.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingBackgroundView.swift
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingContentViewController.swift
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingContentViewController.xib
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingPayload.swift
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingService+Objc.swift
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingService.swift
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingViewController.swift
  src/ui/osx/TogglDesktop/Feature/Onboarding/OnboardingViewController.xib
  src/ui/osx/TogglDesktop/Feature/TimeEntry/Views/TimeEntryCollectionView.m
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/MainDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineActivityRecorderViewController.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/Media.xcassets/Colors/onboarding-background-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Media.xcassets/Colors/onboarding-hint-background-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Other/TogglDesktop-Bridging-Header.h
  src/ui/osx/TogglDesktop/TimeEntryListViewController.h
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimeEntryListViewController.xib
  src/ui/osx/TogglDesktop/TimerEditViewController.h
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/TimerEditViewController.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/TimeEntryCell.m
Labels: macOs

#4066 Use /me/flags to determine which syncing strategy to use
  src/const.h
  src/context.cc
  src/context.h
Labels: lib

#4097 Password Strength view (Windows)
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/EnumEqualToVisibilityConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ErrorTemplate.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Icons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/PasswordBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/LoginViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/PasswordEx.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PasswordRuleView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PasswordRuleView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml.cs
Labels: windows

#4101 Remove all success Password view
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordRuleView.swift
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordStrengthView.swift
  src/ui/osx/TogglDesktop/Feature/PasswordStrength/PasswordStrengthView.xib
Labels: macOs

#4086 Account locking error messages
  src/const.h
  src/https_client.cc
  src/https_client.h
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/LoginViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/IMainView.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/OverlayView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: lib

#4105 Only Load Country API from Sign Up View (mac)
  src/ui/osx/TogglDesktop/LoginViewController.m
Labels: bug, macOs
