Repository toggl-open-source/toggldesktop, pull requests merged in 2020-04, with the labels that each got.

#3954 Fix Windows app not respecting the default project
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/MiniTimer.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml.cs
Labels: bug, windows

#3965 Menu isn't responsive after launching the app
  src/ui/osx/TogglDesktop/TogglDesktop-AppStore-Info.plist
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/TogglDesktop-Info.plist
Labels: bug, macOs

#3980 Windows UI improvements based on feedback from the beta release
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Notifications.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Window.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/TimeEntryCellStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/MiniTimer.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCellDayHeader.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Win32.cs
Labels: windows

#3991 Added logic to show notification when update is ready to be installed
  src/ui/osx/TogglDesktop/AboutWindowController.m
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/UserNotificationCenter.h
  src/ui/osx/TogglDesktop/test2/UserNotificationCenter.m
Labels: macOs

#3976 Show suggestion also when there is a running entry
  src/context.cc
Labels: lib, windows

#4006 Fix the installer to not create a faulty shortcut during auto-update
  dist/windows/TogglDesktopInstaller-x64.nsi
  dist/windows/TogglDesktopInstaller-x86.nsi
Labels: bug, windows

#3986 Fix Apple Sign In Review
  src/context.cc
  src/error.cc
  src/error.h
  src/gui.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/LoginViewController.h
  src/ui/osx/TogglDesktop/LoginViewController.m
  src/ui/osx/TogglDesktop/LoginViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/TogglDesktop-AppStore-Info.plist
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/TogglDesktop-Info.plist
Labels: bug, macOs

#4010 Fix crash during autocomplete
  src/ui/windows/TogglDesktop/TogglDesktop/ui/UIExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutoCompletionPopup.xaml.cs
Labels: bug, windows

#4000 Disable "Disable Library Validation"
  src/ui/osx/TogglDesktop/TogglDesktop/TogglDesktop-AppStore.entitlements
  src/ui/osx/TogglDesktop/TogglDesktop/TogglDesktop.entitlements
Labels: macOs

#4002 Days of week selector component
  src/ui/windows/TogglDesktop/TogglDesktop.Tests/TogglDesktop.Tests.csproj
  src/ui/windows/TogglDesktop/TogglDesktop.Tests/UIUnitTests.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/DaysOfWeekSelector.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/DaysOfWeekSelector.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/DayOfWeekExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/LinqExtensions.cs
Labels: windows

#3984 Memory Leaking Fix
  src/analytics.cc
  src/context.cc
  src/context.h
  src/https_client.cc
  src/https_client.h
  src/timeline_uploader.cc
  src/toggl_api.cc
  src/toggl_api_private.cc
  src/toggl_api_private.h
  src/websocket_client.cc
Labels: bug, lib

#4013 Fix possible crashes during auto-update
  src/ui/windows/TogglDesktop/TogglDesktop/Services/NsisPackageExtractor.cs
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
Labels: windows

#4017 Rename local db name to toggldesktop.db
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
Labels: enhancement, macOs

#4018 Fix Dropdown location for non-default popup alignment
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/PopupAlignmentAwareConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ComboBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/DatePicker.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutoCompletionPopup.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml
Labels: windows

#4020 Scroll to top of the visible Timeline TimeEntry (mac)
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
Labels: bug, macOs
