Repository toggl-open-source/toggldesktop, pull requests merged in 2020-09, with the labels that each got.

#4372 Improve Editor stability by removing possible nil TE (mac)
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/AutoComplete/Input/ProjectAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/Project/ProjectCreationView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController.swift
Labels: macOS

#4387 Update the Reports link to use track.toggl.com
  src/urls.cc
Labels: lib

#4391 "Log out" should be written separately
  src/ui/linux/TogglDesktop/mainwindowcontroller.ui
  src/ui/osx/TogglDesktop/App/AppDelegate.m
  src/ui/osx/TogglDesktop/Features/MainMenu/Base.lproj/MainMenu.xib
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
Labels: linux, macOS, windows

#4394 Timeline UI branch
  src/context.cc
  src/gui.cc
  src/gui.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/DatePicker.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/DatePickerTimelineStyle.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Icons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimelineViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimerEntryListViewViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/DatePickerHelper.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timeline.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timeline.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#4399 Adapt autocomplete dropdown for app size updates (mac)
  src/ui/osx/TogglDesktop/Features/AutoComplete/AutoCompleteInput.h
  src/ui/osx/TogglDesktop/Features/AutoComplete/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4400 Fix Bugsnag configuration to run in Release only (mac)
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4402 Fix bug with description autocomplete empty after startup (mac)
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewModel.swift
Labels: macOS

#4404 Fix description label color on Touch Bar (mac)
  src/ui/osx/TogglDesktop/Features/TouchBar/TimeEntryScrubberItem.xib
Labels: macOS

#4412 Fix errors when updating tags in the local database
  src/database/database.cc
Labels: lib

#4413 Add client name to recent time entries autocomplete
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutoCompletionPopup.xaml
Labels: windows

#4433 Fixed Preferences layout for Big Sur (mac)
  src/ui/osx/TogglDesktop/Features/Preferences/PreferencesWindowController.m
  src/ui/osx/TogglDesktop/Features/Preferences/PreferencesWindowController.xib
Labels: bug, macOS

#4460 Fix bug with in-app message not showing on app start (mac)
  src/ui/osx/TogglDesktop/Common/Extensions/NSView+Ext.swift
  src/ui/osx/TogglDesktop/Features/MainWindow/MainWindowController.m
Labels: bug, macOS

#4461 In-app messages - allow showing the message for chosen platforms only
  src/context.cc
Labels: lib

#4457 Configure in-app message for timer survey launch
  releases/message.json
Labels: macOS

#4467 Fix billable when applying description autocomplete
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewModel.swift
Labels: macOS

#4469 Add Linux dev release to GA
  .github/workflows/main.yml
Labels: actions, linux
