Repository toggl-open-source/toggldesktop, pull requests merged in 2020-02, with the labels that each got.

#3632 Update Xcode 11.3 on macOS build
  src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOs

#3652 Update latest cocoapod
  src/ui/osx/Gemfile
  src/ui/osx/Gemfile.lock
  src/ui/osx/Podfile.lock
Labels: macOs

#3768 MessageBox design update
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/KeyboardShortcuts.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Window.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DialogStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/TogglWindowStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/chrome/ChromelessWindow.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/chrome/TogglChrome.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/chrome/TogglChrome.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/chrome/TogglChromeDesignTimeConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/chrome/TogglWindow.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MessageBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MessageBox.xaml.cs
Labels: windows

#3779 Clear auth info before logging
  src/https_client.cc
Labels: lib

#3777 Toast notifications UI implementation
  src/gui.cc
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ComboBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/HotKeyBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/MahApps.Overrides.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Notifications.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/PasswordBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DialogStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerNotification.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ErrorBar.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PomodoroNotification.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/PomodoroNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ReminderNotification.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ReminderNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TogglNotification.cs
Labels: windows

#3741 Tracking user activity
  src/analytics.cc
  src/analytics.h
  src/context.cc
  src/context.h
Labels: macOs

#3789 Track active view by OS
  src/analytics.cc
  src/analytics.h
  src/context.cc
Labels: lib

#3771 Implement Time entry list UI
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/EmptyStringToCollapsedConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Experiments/implementations/Experiment87Screen.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ModelExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Window.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/TimeEntryCellStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Theming/Theme.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen1.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/DayHeaderViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/ProjectLabelViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimeEntryCellViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimeEntryLabelViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/ViewModelExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/MiniTimer.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/MiniTimer.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectLabel.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectLabel.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/StatusBar.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCell.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCell.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCellContextMenuCommands.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCellDayHeader.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCellDayHeader.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCellDragImposter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryInfoPanel.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryInfoPanel.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryLabel.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryLabel.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TrayToolTipControl.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/IMainView.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/OverlayView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/OverlayView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/LinqExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/utilities/Win32.cs
Labels: windows

#3791 [NEED HELP] Memory Leak in Timeline
  src/formatter.cc
  src/gui.cc
  src/gui.h
  src/lib/osx/Kopsik/MacOSVersionChecker.mm
  src/toggl_api.h
  src/toggl_api_private.cc
  src/toggl_api_private.h
  src/ui/osx/TogglDesktop/Feature/TimeEntry/Views/TimeEntryCollectionView.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineActivity.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineData.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineTimestamp.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineActivityCell.swift
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimeEntryViewItem.h
  src/ui/osx/TogglDesktop/TimeEntryViewItem.m
  src/ui/osx/TogglDesktop/Utils.m
  src/ui/osx/TogglDesktop/idler.c
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/test2/TimelineDisplayCommand.m
Labels: bug, lib

#3784 Correct Arrow position of the Activity Popover
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
Labels: bug, macOs

#3798 Change the Shortcut to switch to next/previous Timeline Day
  src/ui/osx/TogglDesktop/test2/Base.lproj/MainMenu.xib
Labels: bug

#3803 Better Touch Bar v2
  src/ui/osx/TogglDesktop/Feature/TouchBar/TouchBar+PrivateAPIs.m
  src/ui/osx/TogglDesktop/Feature/TouchBar/TouchBarService.swift
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/IdleNotificationWindowController.m
  src/ui/osx/TogglDesktop/test2/TouchBar+PrivateAPIs.h
Labels: bug, macOs

#3782 Resize Timeline feature
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineTimeEntry.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineActivityCell.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineActivityCell.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineBackgroundView.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineBaseCell.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineResizeHoverController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineResizeHoverController.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineTimeEntryCell.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineTimeEntryCell.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOs

#3807 Current Moment Timeline
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineData.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineFlowLayout.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineBaseCell.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineLineView.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineLineView.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineTimeEntryCell.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOs

#3796 Timeline Drag and Drop v1
  src/context.cc
  src/context.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineData.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDraggingSession.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineFlowLayout.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineBackgroundCell.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineBackgroundCell.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineBaseCell.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineLineView.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineLineView.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineTimeEntryCell.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOs

#3801 Improve TogglDesktop Networking
  src/https_client.cc
Labels: lib

#3820 Autotracker tab UI
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/AutotrackerNotificationStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/AutotrackerStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ErrorTemplate.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/TextBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/SharedStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerRuleItem.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerRuleItem.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerSettings.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerSettings.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectTextBox.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml
Labels: windows

#3823 Use ReactiveUI.Fody to reduce viewmodel boilerplate code
  src/ui/windows/TogglDesktop/TogglDesktop/FodyWeavers.xml
  src/ui/windows/TogglDesktop/TogglDesktop/FodyWeavers.xsd
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/DayHeaderViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/FeedbackWindowViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/LoginViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/PreferencesWindowViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/ProjectLabelViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimeEntryCellViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimeEntryLabelViewModel.cs
Labels: windows

#3825 No Entries screens UI
  src/context.cc
  src/context.h
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/Resources/spider.png
  src/ui/windows/TogglDesktop/TogglDesktop/Resources/stopwatch.png
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/EnumEqualToVisibilityConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimeEntryListViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml.cs
Labels: windows

#3830 No Access screen UI
  src/ui/windows/TogglDesktop/TogglDesktop/Resources/restricted-area.png
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Hyperlink.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/OverlayView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/OverlayView.xaml.cs
Labels: windows

#3837 Temporary remove the failed linux test on GA
  .github/workflows/main.yml
Labels: bug

#3835 Tray icon tooltip UI update
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimeEntryLabelViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/MiniTimer.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryInfoPanel.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TrayToolTipControl.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TrayToolTipControl.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#3847 Project ToolTip UI
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/CheckBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ComboBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/DatePicker.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/PasswordBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/TextBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ToolTip.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/SharedStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/ProjectLabelViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutoCompletionPopup.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectLabel.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectToolTip.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectToolTip.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryLabel.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml
Labels: windows

#3648 Prevent update Duration for a running TimeEntry if the text isn't changed from users
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/test2/EditableTextField.h
  src/ui/osx/TogglDesktop/test2/EditableTextField.m
  src/ui/osx/TogglDesktop/test2/UndoTextField.h
Labels: bug, macOs

#3850 Update to MahApps.Metro 2.0
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/ActivateParentWindowOnMouseClick.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/CloseWindowOnEscBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/DatePickerKeyboardHandlingBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/FocusParentWindowOnClosingBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/HideWindowOnClosingBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/NumericInputTextBoxBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/RepositionPopupWithParentWindowBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ComboBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ContextMenu.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/DatePicker.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ErrorTemplate.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ListBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/MahApps.Overrides.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/PasswordBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/TabControl.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/TextBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ToggleSwitch.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ToolTip.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/PreferencesWindowViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/AboutWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/EditViewPopup.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/IdleNotificationWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MessageBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/PreferencesWindow.xaml
Labels: windows

#3843 Ease of project creation by keyboard
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AutoComplete/DataSource/ProjectDataSource.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
Labels: macOs

#3860 Select default workspace instead of first workspace
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Project/ProjectCreationView.swift
Labels: macOs

#3836 Create Empty TE without stopping the current running TE
  src/context.cc
  src/context.h
  src/test/app_test.cc
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineData.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/user.cc
  src/user.h
Labels: bug, macOs

#3854 FixTimeline Editor doesn't update TE data properly
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
Labels: bug, macOs

#3857 Scrollbar design update implementation
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ScrollBar.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Window.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/ScrollBarStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml
Labels: windows

#3859 Track the usage of expand/collapse days functionality
  src/context.cc
  src/context.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglApi.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryList.xaml.cs
Labels: windows

#3862 Calendar design update
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Behaviors/DatePickerKeyboardHandlingBehavior.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Calendar.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/DatePicker.xaml
Labels: windows
