Repository toggl-open-source/toggldesktop, pull requests merged in 2020-12, with the labels that each got.

#4726 Fix small TE layout on timeline (mac)
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineTimeEntryCell.xib
Labels: macOS

#4729 Fix failing GH Actions on Linux
  .github/workflows/main.yml
Labels: actions, linux

#4734 Fix crash with NullReferenceException in Tutorial
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/SharedStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen2.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen3.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen4.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen5.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen6.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen7.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Tutorial/BasicTutorialScreen7.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimerViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#4740 Don't set stop time if it's not valid (lib)
  src/model/time_entry.cc
  src/model/time_entry.h
  src/test/app_test.cc
Labels: macOS

#4750 Fix Editor color when switching between dark/light modes (mac)
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/EditorPopover.swift
Labels: macOS

#4751 Fix TE background color with dark mode switch (mac)
  src/ui/osx/TogglDesktop/Common/Extensions/NSColor+Theme.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/CornerBoxView.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineTimeEntryCell.swift
Labels: macOS

#4748 Refactor colors on macOS
  src/ui/osx/TogglDesktop/.swiftlint.yml
  src/ui/osx/TogglDesktop/.xiblint.json
  src/ui/osx/TogglDesktop/Common/Extensions/NSColor+Theme.swift
  src/ui/osx/TogglDesktop/Common/Extensions/NSColor+Utils.swift
  src/ui/osx/TogglDesktop/Common/Extensions/NSView+Shadow+Border.swift
  src/ui/osx/TogglDesktop/Common/Utils/ProjectTitleFactory.swift
  src/ui/osx/TogglDesktop/Common/Views/SelectableButton.swift
  src/ui/osx/TogglDesktop/Features/About/AboutWindowController.m
  src/ui/osx/TogglDesktop/Features/Auth/LoginViewController.m
  src/ui/osx/TogglDesktop/Features/Auth/PasswordStrength/PasswordRuleView.swift
  src/ui/osx/TogglDesktop/Features/Auth/PasswordStrength/PasswordStrengthView.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/Views/AutoCompleteRowView.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/Views/TagCell/TagCellView.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteTableContainer.m
  src/ui/osx/TogglDesktop/Features/Calendar/Cell/DateCellViewItem.swift
  src/ui/osx/TogglDesktop/Features/Onboarding/OnboardingBackgroundView.swift
  src/ui/osx/TogglDesktop/Features/SystemMessage/FloatingErrorView.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/ProjectCreation/ProjectCreationView.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/Views/DateSelectionView/DatePickerView.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryList/TimeEntryDatasource.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryList/Views/TimeDecoratorView.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Models/TimelineActivity.swift
  src/ui/osx/TogglDesktop/Features/Timeline/OGSwitch.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/PanelSwitcherButton.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineBackgroundCell.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineDividerView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerContainerBox.swift
  src/ui/osx/TogglDesktop/Features/TouchBar/LoginSignupTouchBar.swift
  src/ui/osx/TogglDesktop/Resources/Colors.swift
  src/ui/osx/TogglDesktop/Resources/Media.xcassets/Colors/Contents.json
  src/ui/osx/TogglDesktop/Resources/Media.xcassets/Colors/border-default.colorset/Contents.json
  src/ui/osx/TogglDesktop/Resources/Media.xcassets/Colors/shadow.colorset/Contents.json
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4757 Display actual workspace name (mac)
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/Models/AutocompleteItem.m
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/Models/TimeEntryViewItem.m
Labels: macOS

#4758 Fix activity menu tooltip about total time (mac)
  src/ui/osx/TogglDesktop/App/AppDelegate.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4766 Fix label behaviour on Timeline TE (mac)
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineTimeEntryCell.xib
Labels: macOS

#4763 Vertically center text on project select button (mac)
  src/ui/osx/TogglDesktop/Common/Views/TextFields/VerticallyCenteredTextFieldCell.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.xib
Labels: macOS

#4768 Update Bundler (mac)
  src/ui/osx/Gemfile.lock
Labels: macOS

#4771 Show zoom button on Timeline at all times
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.swift
Labels: macOS

#4772 Close duration dropdown when user clicks the List/Timeline tabs
  src/ui/osx/TogglDesktop/Features/Timeline/MainDashboardViewController.swift
Labels: macOS

#4773 Update time when duration dropdown is closed (mac)
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
Labels: macOS

#4770 Remove hardcoded colors (mac)
  src/ui/osx/TogglDesktop/Common/Views/TextFields/ProjectTextField.m
  src/ui/osx/TogglDesktop/Features/About/AboutWindowController.m
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteTableCell.m
  src/ui/osx/TogglDesktop/Features/Feedback/FeedbackWindowController.m
  src/ui/osx/TogglDesktop/Features/IdleNotification/IdleNotificationWindowController.m
  src/ui/osx/TogglDesktop/Features/TimeEntryList/TimeEntryCell.m
  src/ui/osx/TogglDesktop/Features/TimeEntryList/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/Features/Timeline/Models/TimelineActivity.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineDashedCornerView.swift
  src/ui/osx/TogglDesktop/Resources/Colors.swift
  src/ui/osx/TogglDesktop/Resources/Media.xcassets/Colors/Timeline/timeline-dashed-box-border.colorset/Contents.json
  src/ui/osx/TogglDesktop/Resources/Media.xcassets/Colors/disabled-restart-button-background.colorset/Contents.json
  src/ui/osx/TogglDesktop/Resources/Media.xcassets/Colors/preference-background-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/Resources/Media.xcassets/Colors/upload-background-color.colorset/Contents.json
Labels: macOS

#4777 Clean git repo before proceeding with release script
  dist/update_releases.sh
Labels: actions, macOS
