Repository toggl-open-source/toggldesktop, pull requests merged in 2020-07, with the labels that each got.

#4228 Fix BaseModel database performance by not making it dirty everytime
  src/model/autotracker.cc
  src/model/base_model.cc
  src/model/client.cc
  src/model/obm_action.cc
  src/model/project.cc
  src/model/tag.cc
  src/model/task.cc
  src/model/time_entry.cc
  src/model/timeline_event.cc
  src/model/user.cc
  src/model/workspace.cc
  src/util/property.h
Labels: lib

#4171 SSO Feature on macOS
  src/const.h
  src/context.cc
  src/context.h
  src/gui.cc
  src/gui.h
  src/https_client.cc
  src/https_client.h
  src/toggl_api.cc
  src/toggl_api.h
  src/types.h
  src/ui/osx/TogglDesktop/Feature/SSO/SSOService+Objc.swift
  src/ui/osx/TogglDesktop/Feature/SSO/SSOService.swift
  src/ui/osx/TogglDesktop/Feature/SystemMessage/SystemMessage.swift
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/LoginViewController.h
  src/ui/osx/TogglDesktop/LoginViewController.m
  src/ui/osx/TogglDesktop/LoginViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/Media.xcassets/Colors/login-text-color.colorset/Contents.json
  src/ui/osx/TogglDesktop/TogglDesktop-AppStore-Info.plist
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/UIEvents.h
  src/ui/osx/TogglDesktop/UIEvents.m
  src/ui/osx/TogglDesktop/test2/AppDelegate.h
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/TogglDesktop-Info.plist
Labels: macOS

#4236 Fix the linux tarball build
  .github/workflows/main.yml
  dist/linux/install-qt.sh
Labels: actions, linux

#4239 Upload macOS app installers as artifacts
  .github/workflows/main.yml
Labels: actions, macOS

#4262 [WIP] Rebranding - update staging url domain
  src/urls.cc
  src/websocket_client.cc
Labels: lib

#4277 Do not set focus to project text box after new client is created
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/EditView.xaml.cs
Labels: windows
