Repository toggl-open-source/toggldesktop, pull requests merged in 2020-08, with the labels that each got.

#4297 Move to desktop.track.toggl.com for production endpoints
  src/urls.cc
Labels: lib

#4315 Update Windows in-app notification style to reflect the new design
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/StringToUpperConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/InAppNotification.xaml
Labels: windows

#4331 Kill the app process when the updater is launched
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
Labels: windows

#4333 Install pending updates as close to app startup as possible
  src/ui/windows/TogglDesktop/TogglDesktop/BugsnagService.cs
  src/ui/windows/TogglDesktop/TogglDesktop/Program.cs
  src/ui/windows/TogglDesktop/TogglDesktop/Services/UpdateService.cs
  src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/AboutWindowViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: windows

#4318 Reduce workspace/preferences and preferences/desktop fetches (v2)
  src/context.cc
  src/context.h
  src/model/time_entry.cc
  src/model/time_entry.h
Labels: lib

#4316 In-app notification about the upcoming rebranding
  releases/message.json
  src/context.cc
Labels: lib

#4344 Start fetching in-app messages on user login instead of app startup
  src/context.cc
Labels: lib

#4361 Rename macOS app executable name
  dist/osx/appcast_template.xml
  dist/osx/build.sh
  src/ui/osx/TogglDesktop/App/AppDelegate.m
  src/ui/osx/TogglDesktop/Common/Views/TextFields/NSTextFieldClickable.m
  src/ui/osx/TogglDesktop/Common/Views/TextFields/ProjectTextField.m
  src/ui/osx/TogglDesktop/Features/About/AboutWindowController.m
  src/ui/osx/TogglDesktop/Features/Auth/LoginViewController.m
  src/ui/osx/TogglDesktop/Features/AutoComplete/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/Features/AutoComplete/AutoCompleteTableCell.m
  src/ui/osx/TogglDesktop/Features/AutoComplete/LiteAutoCompleteDataSource.m
  src/ui/osx/TogglDesktop/Features/Feedback/FeedbackWindowController.m
  src/ui/osx/TogglDesktop/Features/IdleNotification/IdleNotificationWindowController.m
  src/ui/osx/TogglDesktop/Features/MainMenu/et.lproj/MainMenu.strings
  src/ui/osx/TogglDesktop/Features/MainWindow/MainWindowController.m
  src/ui/osx/TogglDesktop/Features/Preferences/PreferencesWindowController.m
  src/ui/osx/TogglDesktop/Features/SystemMessage/FloatingErrorView.xib
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/AutoComplete/KeyboardTableView.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryList/TimeEntryCell.m
  src/ui/osx/TogglDesktop/Features/TimeEntryList/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/Features/TimeEntryList/Views/TimeEntryCollectionView.m
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerEditViewController.m
  src/ui/osx/TogglDesktop/Supporting Files/TogglDesktop-AppStore-Info.plist
  src/ui/osx/TogglDesktop/Supporting Files/TogglDesktop-Info.plist
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/xcshareddata/xcschemes/TogglDesktop-AppStore-Production.xcscheme
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/xcshareddata/xcschemes/TogglDesktop-AppStore.xcscheme
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/xcshareddata/xcschemes/TogglDesktop-Production.xcscheme
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/xcshareddata/xcschemes/TogglDesktop.xcscheme
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/Models/AutocompleteItem.m
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/Models/TimeEntryViewItem.m
Labels: macOS
