Repository toggl-open-source/toggldesktop, pull requests merged in 2020-11, with the labels that each got.

#4632 Feature/duration dropdown basics
  src/ui/osx/TogglDesktop/Common/Extensions/NSView+Xib.swift
  src/ui/osx/TogglDesktop/Common/Utils/ObservationToken.swift
  src/ui/osx/TogglDesktop/Common/Utils/ResponderObservable.swift
  src/ui/osx/TogglDesktop/Common/Views/DropdownWindow.swift
  src/ui/osx/TogglDesktop/Common/Views/TextFields/ResponderTextField.swift
  src/ui/osx/TogglDesktop/Features/Auth/PasswordStrength/PasswordStrengthView.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/AutoCompleteView.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/Input/AutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/Input/ProjectAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/ResponderAutoCompleteInput.swift
  src/ui/osx/TogglDesktop/Features/Calendar/CalendarViewController.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/ProjectCreation/ProjectCreationView.swift
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerContainerBox.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerDurationControl.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerDurationControl.xib
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4637 Prevent possible crash when emptyActivityLbl is not yet loaded (mac)
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.swift
Labels: bug, macOS

#4639 Implement start time update via duration dropdown (mac)
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Features/Calendar/Date+Utils.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerDurationControl.swift
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.m
Labels: macOS

#4646 Implement date control on duration dropdown (mac)
  src/ui/osx/TogglDesktop/Features/Calendar/Date+Utils.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerDurationControl.swift
Labels: macOS

#4648 Track usage analytics of duration dropdown (mac)
  src/analytics.cc
  src/analytics.h
  src/context.cc
  src/context.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.m
Labels: macOS

#4654 Remove the ability to open Edit popover for running entry from Timer
  src/ui/osx/TogglDesktop/Features/Timer/TimerEditViewController/TimerEditViewController.h
  src/ui/osx/TogglDesktop/Features/Timer/TimerEditViewController/TimerEditViewController.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerDurationControl.swift
Labels: macOS

#4668 Feature/duration dropdown improvements
  src/ui/osx/TogglDesktop/Features/Timer/TimerEditViewController/TimerEditViewController.m
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerDurationControl.swift
Labels: macOS

#4681 Use environment files instead of set-env (actions)
  .github/workflows/main.yml
Labels: actions

#4679 Fix "date change" analytics sending at app launch (mac)
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
Labels: macOS

#4680 Include duration dropdown date controls into key loop for everyone (mac)
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/Views/CursorButton.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimeEditView.swift
Labels: macOS

#4687 Update macOS build settings
  .github/workflows/main.yml
  README.md
  src/lib/osx/TogglDesktopLibrary.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4683 Truncate TE description on Timeline (mac)
  src/ui/osx/TogglDesktop/Common/Utils/ProjectTitleFactory.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineTimeEntryCell.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineTimeEntryCell.xib
Labels: macOS

#4672 Fix table view padding for Big Sur (mac)
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/AutoCompleteView.xib
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteTable.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4698 Fix height of error message view on Big Sur (mac)
  src/ui/osx/TogglDesktop/Features/MainWindow/MainWindowController.m
Labels: macOS

#4709 Stop sending sync requests when time entry fails to sync
  src/context.cc
  src/database/database.cc
  src/model/base_model.cc
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimeEntryCellViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCell.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCell.xaml.cs
Labels: lib

#4711 Fix crash in unit tests when initializing UpdateManager
  src/ui/windows/TogglDesktop/TogglDesktop/Services/UpdateService.cs
Labels: windows

#4713 Fix zoom out button size (mac)
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.xib
Labels: macOS

#4714 Activate start button on Enter key press (mac)
  src/ui/osx/TogglDesktop/Common/Views/CursorButton.swift
  src/ui/osx/TogglDesktop/Common/Views/CustomFocusRingButton.swift
  src/ui/osx/TogglDesktop/Common/Views/HoverButton.swift
  src/ui/osx/TogglDesktop/Common/Views/KeyButton.swift
  src/ui/osx/TogglDesktop/Common/Views/NSHoverButton.h
  src/ui/osx/TogglDesktop/Common/Views/NSHoverButton.m
  src/ui/osx/TogglDesktop/Common/Views/TextFields/VerticallyCenteredTextFieldCell.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/Views/CursorButton.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.xib
  src/ui/osx/TogglDesktop/Supporting Files/TogglDesktop-Bridging-Header.h
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS
