Repository toggl-open-source/toggldesktop, pull requests merged in 2020-01, with the labels that each got.

#3669 Fix crash when displaying in-app notification
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/InAppNotification.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/MainWindow.xaml.cs
Labels: bug, windows

#3642 Open Timer Editor in Timeline mode
  src/ui/osx/TogglDesktop/TimeEntryListViewController.m
  src/ui/osx/TogglDesktop/TimerEditViewController.m
Labels: bug, macOs

#3677 Fix menu on right click doesn't show on Overlap Time Entry
  src/ui/osx/TogglDesktop/Feature/Timeline/Views/TimelineTimeEntryCell.swift
Labels: macOs

#3679 Fix the TrackingArea in Date Label in calendar
  src/ui/osx/TogglDesktop/Feature/Calendar/Cell/DateCellViewItem.swift
Labels: bug, macOs

#3682 Timeline: Misaligned activity label
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineFlowLayout.swift
Labels: bug, macOs

#3683 Timeline: Should close other Popovers when popover is presented
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DateSelectionView/DatePickerView.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
Labels: bug, macOs

#3691 Login view improvements
  src/ui/windows/TogglDesktop/TogglDesktop.sln.DotSettings
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Buttons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ComboBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ContextMenu.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/MahApps.Overrides.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ToggleSwitch.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/LoginViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/LoginView.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/windows/FeedbackWindow.xaml
Labels: windows

#3634 Fix blurred icon app in 10.12
  src/ui/osx/TogglDesktop/test2/AppIconFactory.m
Labels: bug, macOs

#3726 Main window Timer design update
  src/ui/windows/TogglDesktop/TogglDesktop/App.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/StringPrependConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Icons.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/MahApps.Overrides.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/TextBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/SharedStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/TimerStyles.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectLabel.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/ProjectLabel.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timer.xaml.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/TimerEntryListView.xaml.cs
Labels: windows

#3735 Autocomplete items design update
  src/ui/windows/TogglDesktop/TogglDesktop/AutoCompletion/AutoCompleteController.cs
  src/ui/windows/TogglDesktop/TogglDesktop/TogglDesktop.csproj
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/BindingProxy.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/ColorsToBrushConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/EmptyStringToHiddenConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Converters/IsNotNegativeConverter.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Controls.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/ListBox.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/Typography.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Dark.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/Themes/ColorScheme/Light.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutoCompletionPopup.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/AutotrackerSettings.xaml
Labels: windows

#3663 Add a lightweight VS solution without Poco projects
  src/database.cc
  src/lib/windows/TogglDesktopDLL/TogglDesktopDLL.vcxproj
  src/ui/windows/TogglDesktop/TogglDesktop.NoPoco.sln
Labels: windows

#3745 Menu cleanup for timeline
  src/ui/osx/TogglDesktop/MenuItemTags.h
  src/ui/osx/TogglDesktop/test2/AppDelegate.m
  src/ui/osx/TogglDesktop/test2/Base.lproj/MainMenu.xib
Labels: macOs

#3752 Add shortcut to switch to next or previous day
  src/ui/osx/TogglDesktop/Feature/Timeline/MainDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/MainWindowController.m
  src/ui/osx/TogglDesktop/test2/Base.lproj/MainMenu.xib
Labels: macOs

#3657 Remove UPPERCASE of Workspace names
  src/related_data.cc
  src/ui/linux/TogglDesktop/autocompleteview.h
  src/ui/osx/TogglDesktop/AutocompleteItem.m
  src/ui/osx/TogglDesktop/TimeEntryViewItem.m
  src/ui/windows/TogglDesktop/TogglDesktop/AutoCompletion/AutoCompleteController.cs
  src/ui/windows/TogglDesktop/TogglDesktop/AutoCompletion/ListBoxItem.cs
Labels: lib

#3426 Fix race condition in loadUserTimeEntryFromJSON
  src/context.cc
  src/time_entry.cc
  src/user.cc
  src/user.h
Labels: lib

#3607 Fix IsPostponed() library method
  src/const.h
  src/context.cc
Labels: lib, windows

#3658 Support Undo Deleted Time Entry
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Feature/TimeEntry/Views/TimeEntryCollectionView.m
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/EditorViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineData.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/TimerEditViewController.m
  src/ui/osx/TogglDesktop/Utils.h
  src/ui/osx/TogglDesktop/Utils.m
  src/ui/osx/TogglDesktop/test2/TimeEntryCell.h
  src/ui/osx/TogglDesktop/test2/TimeEntryCell.m
Labels: lib, macOs

#3760 Fix missing AppStore scheme for Timeline
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: bug, macOs

#3728 Persistent Active tab state: Timeline and Time Entry List
  src/analytics.cc
  src/context.cc
  src/context.h
  src/database.cc
  src/database.h
  src/gui.h
  src/migrations.cc
  src/settings.cc
  src/settings.h
  src/toggl_api.cc
  src/toggl_api.h
  src/toggl_api_private.cc
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/Feature/Timeline/MainDashboardViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineDashboardViewController.swift
Labels: macOs

#3757 Add mac timeline ui "learn more" link
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineActivityRecorderViewController.swift
  src/ui/osx/TogglDesktop/Feature/Timeline/TimelineActivityRecorderViewController.xib
Labels: macOs

#3739 Timeline Gap Entry issues
  src/ui/osx/TogglDesktop/Feature/Timeline/Models/TimelineData.swift
Labels: bug, macOs

#3763 Fix sub-entries display on Windows
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCell.xaml.cs
Labels: windows
