Repository toggl-open-source/toggldesktop, pull requests merged in 2020-10, with the labels that each got.

#4480 Update macOS app icon (mac)
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running1024.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running128.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running16.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running256-1.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running256.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running32-1.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running32.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running512-1.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running512.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/Running64.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-1024px.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-128px.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-16px.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-256px-1.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-256px.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-32px-1.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-32px.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-512px 2-1.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-512px 2.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIcon.appiconset/track-macOS-running-64px.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIconNotRunning.imageset/AppIcon-256.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIconNotRunning.imageset/AppIcon-512.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIconNotRunning.imageset/Contents.json
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIconNotRunning.imageset/track-macOS-stopped-256px.png
  src/ui/osx/TogglDesktop/Resources/Images.xcassets/AppIconNotRunning.imageset/track-macOS-stopped-512px 2.png
Labels: macOS

#4503 Use new cert for MS Store app in CI
  .github/workflows/main.yml
Labels: windows

#4493 Add @ shortcut to open project selection when typing TE description
  src/ui/osx/TogglDesktop/Common/Extensions/Comparable+Utils.swift
  src/ui/osx/TogglDesktop/Common/Extensions/String+Search.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/AutoCompleteInput.h
  src/ui/osx/TogglDesktop/Features/AutoComplete/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/AutoComplete/AutoCompleteView.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/AutoComplete/DataSource/AutoCompleteViewDataSource.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/AutoComplete/Input/TagAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/AutoComplete/KeyboardTableView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerEditViewController/TimerEditViewController.h
  src/ui/osx/TogglDesktop/Features/Timer/TimerEditViewController/TimerEditViewController.m
  src/ui/osx/TogglDesktop/Features/Timer/TimerEditViewController/TimerEditViewController.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/AutocompleteSourceViewType.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerDescriptionFieldHandler.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.xib
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/Views/TimerContainerBox.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/xcshareddata/xcschemes/TogglDesktop.xcscheme
  src/ui/osx/TogglDesktop/TogglDesktopTests/TimerDescriptionFieldHandlerTests.swift
Labels: macOS

#4496 Set strict versions for macOS app dependencies
  src/ui/osx/Gemfile
  src/ui/osx/Gemfile.lock
  src/ui/osx/Podfile
  src/ui/osx/Podfile.lock
  src/ui/osx/TogglDesktop/Features/Onboarding/OnboardingViewController.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/AutoComplete/DataSource/AutoCompleteViewDataSource.swift
  src/ui/osx/TogglDesktop/Features/Timeline/MainDashboardViewController.swift
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.swift
Labels: enhancement, macOS

#4525 Add analytics for description shortcuts tracking (mac)
  src/analytics.cc
  src/analytics.h
  src/context.cc
  src/context.h
  src/toggl_api.cc
  src/toggl_api.h
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerDescriptionFieldHandler.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.m
Labels: macOS

#4470 Change default TE duration to 1 hour
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineCollectionView.swift
Labels: macOS

#4535 Improve popover UX on Timeline
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.swift
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.xib
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDatasource.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineActivityCell.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineBaseCell.swift
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineTimeEntryCell.swift
Labels: macOS

#4533 Upload release asset before updating appcast xml file
  .github/workflows/main.yml
Labels: actions, macOS

#4542 Automatically fill in info from the project that was created from Timer
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/Input/ProjectAutoCompleteTextField.swift
  src/ui/osx/TogglDesktop/Features/TimeEntryEditor/ProjectCreation/ProjectCreationView.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
  src/ui/osx/TogglDesktop/Models/Project.swift
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/project.pbxproj
Labels: macOS

#4547 Fix bug with project creation popup closing when creating client (mac)
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
Labels: macOS

#4552 Fix bug when autocomplete mouse selection wasn't working on macOS
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/Storage/TagStorage.swift
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/LiteAutoCompleteDataSource.m
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerDescriptionFieldHandler.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewController.swift
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
Labels: macOS

#4560 Improve mouse selection on autocomplete list (mac)
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteInput.m
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteTable.h
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteTable.m
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
Labels: macOS

#4564 Remove "Check for update" menu for App Store configuration (mac)
  src/ui/osx/TogglDesktop/App/AppDelegate.m
  src/ui/osx/TogglDesktop/Features/MainMenu/Base.lproj/MainMenu.xib
Labels: macOS

#4551 Speed up loading time entry list
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/ViewModelExtensions.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimeEntryCell.xaml.cs
Labels: windows

#4567 Fix ambiguous layout on Timeline for small time entries
  src/ui/osx/TogglDesktop/Features/Timeline/Views/TimelineTimeEntryPlaceholderCell.xib
Labels: macOS

#4569 Update unit tests for TimerDescriptionFieldHandler
  src/ui/osx/TogglDesktop/TogglDesktopTests/TimerDescriptionFieldHandlerTests.swift
Labels: macOS

#4573 Use SHA-256 for signing Windows binaries
  .github/workflows/main.yml
  dist/windows/TogglDesktopInstaller-x64.nsi
  dist/windows/TogglDesktopInstaller-x86.nsi
  dist/windows/scripts/sign.sh
Labels: windows

#4572 Fix Timeline breaking after drag-creating TE with open Edit (mac)
  src/ui/osx/TogglDesktop/Features/Timeline/TimelineDashboardViewController.swift
Labels: macOS

#4575 Fix Tab not working on description field (mac)
  src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerDescriptionFieldHandler.swift
Labels: macOS

#4584 Fix switching focus from empty tags selection search field (mac)
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/AutoCompleteView.swift
Labels: macOS

#4586 Fix broken autocomplete layout after re-login (mac)
  src/ui/osx/TogglDesktop/Features/AutoComplete/LegacyAutoComplete/AutoCompleteInput.m
Labels: macOS

#4589 Fix DatePicker date format in the Timeline view
  src/ui/windows/TogglDesktop/TogglDesktop/ui/Resources/DesignUpdate/DatePickerTimelineStyle.xaml
Labels: windows

#4599 Allow ignoring SSL verification (mac)
  src/ui/osx/TogglDesktop/Features/Preferences/PreferencesWindowController.m
  src/ui/osx/TogglDesktop/Features/Preferences/PreferencesWindowController.xib
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.h
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/DesktopLibraryBridge.m
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/Models/Settings.h
  src/ui/osx/TogglDesktop/TogglDesktopLibrary/Models/Settings.m
Labels: macOS

#4602 Fix Tab focus change from description field on Edit popup (mac)
  src/ui/osx/TogglDesktop/Features/AutoComplete/GenericAutoComplete/AutoCompleteView.swift
Labels: macOS

#4592 When showing the app, focus the timer description (if available) (linux)
  src/ui/linux/TogglDesktop/mainwindowcontroller.cpp
  src/ui/linux/TogglDesktop/timeentrylistwidget.cpp
  src/ui/linux/TogglDesktop/timeentrylistwidget.h
  src/ui/linux/TogglDesktop/timerwidget.cpp
  src/ui/linux/TogglDesktop/timerwidget.h
Labels: linux

#4596 In the tarball, contain everyting in a root folder
  dist/linux/package.sh
Labels: linux

#4600 Enable constrains visualization only in debug mode (mac)
  src/ui/osx/TogglDesktop/App/AppDelegate.m
  src/ui/osx/TogglDesktop/TogglDesktop.xcodeproj/xcshareddata/xcschemes/TogglDesktop.xcscheme
Labels: macOS

#4618 Fix crash when onboarding is shown before window is loaded (mac)
  src/ui/osx/TogglDesktop/Features/Onboarding/OnboardingViewController.swift
Labels: macOS

#4607 Start autotracker only if a window has been in focus for over 5 seconds
  src/const.h
  src/window_change_recorder.cc
  src/window_change_recorder.h
Labels: lib

#4625 Display task name in the timeline view
  src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimelineViewModel.cs
  src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimelineTimeEntryBlock.xaml
  src/ui/windows/TogglDesktop/TogglDesktop/ui/views/Timeline.xaml
Labels: windows
